// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbxqrpwsbwfyvrafghav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNieHFycHdzYndmeXZyYWZnaGF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwNzcxMTEsImV4cCI6MjA1MzY1MzExMX0.nOc5CG4v0y628O4VWNhdfMhFPKA_1_PdkRTqM9timmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);